project:
  type: website
  output-dir: docs  # This ensures GitHub Pages can find your files

website:
  title: "Interactive Data Visualization with Ipychart"
  navbar:
    right:
      - href: PSDV_Exposition.ipynb  # Ensure correct file reference
        text: Notebook
      - href: blog.qmd
        text: Blog

format:
  html:
    theme:
      light: [litera, styles.scss]
    highlight-style: a11y-dark
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap

execute:
  freeze: auto
